<div class="smashing-action">
	<div class='banner'>
		<img class='logo' src='<?php echo $this->path('wxs.fucms')?>/smashing/image/logo.png' />
		<img class='bg' src='<?php echo $this->path('wxs.fucms')?>/smashing/image/bg.jpg?imageView2/2/w/640' />
	</div>
	<div class='egg-container'>
		<img class='hammer' src='<?php echo $this->path('wxs.fucms')?>/smashing/image/hammer.png' />
		<a class='egg' href="javascript:;">
			<img src="<?php echo $this->path('wxs.fucms')?>/smashing/image/egg-orig.png" data-src="<?php echo $this->path('wxs.fucms')?>/smashing/images/egg2.png"/>
		</a>
	</div>
	<div class='description'>
		<div class="title"><?php echo $this->smashingData['label']?></div>
		<div class="body">
			<?php echo $this->smashingData['explain']?>
		</div>
	</div>
</div>


<?php $this->headLink()->appendStylesheet($this->path('wxs.fucms').'/smashing/style/style.css?v=101'); ?>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script>
	wx.config(<?php echo $this->wxConfig?>);
	window.config = {
		postData: <?php echo $this->postData?>,
		postUrl: '<?php echo $this->postUrl?>',
		snInfoUrl: '<?php echo $this->snInfoUrl?>'
	};
	wx.ready(function(){
		wx.hideOptionMenu();
	});






	$(document).ready(function() {
		var moveUp = true;
		
		function transit() {
			moveUp = !moveUp;
			if (!moveUp) {
				$('.hammer').addClass('end-pos');	
			} else {
				$('.hammer').removeClass('end-pos');
			}
		}
		transit();
		var waveHammer = window.setInterval(function() { transit(); }, 1500);
		
	    var isNotDraw = true;
	    $('.egg-container > a.egg').on('click', function() {
			if(isNotDraw) {
				var _this = $(this),
				eggImg = _this.children('img').eq(0),
				postData = window.config.postData;
				$.post(window.config.postUrl, postData, function(res) {
					
					
					alert(res.status);
					
					isNotDraw = false;
					var newEggImgSrc = eggImg.attr('data-src');
	    
					if(res.status == 'success') {
						$.dialog({
							content	: '恭喜你中奖了，获得了'+res.msg.prizeName,
							title	: "ok",
							ok		: function() {
								location.href = window.config.snInfoUrl+'/'+res.msg.snId;
								return false;
							},
							okText	:'查看详情'
						});
						eggImg.attr('src', newEggImgSrc);
						window.clearInterval(waveHammer);
						$('.hammer').removeClass('end-pos');
						$('.hammer').addClass('smash-pos');
					} else if(res.status == 'error') {
						$.dialog({
							content	: res.msg,
							title	: "alert",
							time	: 5000
						});
						window.clearInterval(waveHammer);
					}
				});
			}
		})
	});















	
</script>
<!-- script src="<?php echo $this->path('wxs.fucms')?>/smashing/script/smashing.js?v=2015050516"></script -->