<div class="smashing-action">
	<div class='banner'>
		<img class='logo' src='<?php echo $this->smashingData['logo']?>?v=20150518' />
		<img class='bg' src='<?php echo $this->path('wxs.fucms')?>/smashing/image/bg.jpg?imageView2/2/w/640' />
	</div>
	<div class='egg-container'>
		<img class='hammer' src='<?php echo $this->path('wxs.fucms')?>/smashing/image/hammer.png' />
		<a class='egg' href="javascript:;">
			<img src="<?php echo $this->path('wxs.fucms')?>/smashing/image/egg-orig.png" data-src="<?php echo $this->path('wxs.fucms')?>/smashing/images/egg2.png"/>
		</a>
	</div>
	<div class='description'>
		<div class="title"><?php echo $this->smashingData['label']?></div>
		<div class="body">
			<?php echo $this->smashingData['explain']?>
		</div>
	</div>
</div>


<?php $this->headLink()->appendStylesheet($this->path('wxs.fucms').'/smashing/style/style.css?v=101'); ?>
<script src="<?php echo $this->path('wxs.fucms')?>/smashing/script/smashing.js?v=20150515"></script>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script>
	wx.config(<?php echo $this->wxConfig?>);
	window.config = {
		postData: <?php echo $this->postData?>,
		postUrl: '<?php echo $this->postUrl?>',
		snInfoUrl: '<?php echo $this->snInfoUrl?>'
	};
	wx.ready(function(){
		wx.hideOptionMenu();
	});
</script>