<div class="user-info">
	<div class="user-icon"><img width="100px" src="<?php echo $this->recordData['headimgurl']?>"></div>
	<div class="user-nickname"><?php echo $this->recordData['nickname']?></div>
	<div class="value">已获取<span><?php echo $this->recordData['value']?></span><?php echo $this->promotionData['unit']?></div>
</div>
<div class="button-main">	
	<?php if($this->openId != $this->partakeInfo['fromId']){?>
	<a class="btn" href="<?php echo $this->promostionUrl?>">我也来参与</a>
	<?php }?>
	<?php if(!$this->partakeInfo['status']){?>
	<button class="btn" id="btn-post">为TA加油助力</button>
	<?php }?>
	<button class="btn" id="btn-help">找人来帮忙</button>
</div>
<div class="promotion-info">
	<div class="promotion-title">
		<h3><?php echo $this->promotionData['label']?></h3>
	</div>
	
	<div>
		<?php echo $this->promotionData['explain']?>
	</div>
</div>

<?php $this->headLink()->appendStylesheet($this->path('wxs.fucms').'/promotion/assistance/style/index.css?v=0810'); ?>


<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script>
	wx.config(<?php echo $this->wxConfig?>);
	window.Config = {
		postData: <?php echo $this->postData?>,
		postUrl: '<?php echo $this->postUrl?>',
		shareData: '<?php echo $this->shareData?>',
		userData: '<?php echo $this->userData?>'
	};
	var shareConfig = '<?php echo $this->shareData?>',
		userData = '<?php echo $this->userData?>';
	wx.ready(function(){
		alert('wx.ready');
	});
	wx.error(function(res){
		alert('error');
		alert(res.msg);
	});
	document.querySelector('#btn-help').onclick = function(){
		alert('click');
		wx.onMenuShareAppMessage({
			title: '朋友们，快来帮我获取更多奖励吧！！',
			desc: '这里是一段分享描述，此处作为测试，固定数据', // 分享描述
			link: shareConfig['link']+'?fromId='+userData['openid'], // 分享链接
			imgUrl: userData['headimgurl'],
			success: function(){},
			cancel: function(){},
		});
		alert('注册成功');
	}
</script>