<?php if($this->errorMsg != "") {?>
<div class="weui_cell weui_cell_warn">
	<div class="weui_cell_bd weui_cell_primary">
		<p style="color: #F43530;"><?php echo $this->errorMsg?></p>
	</div>
	<div class="weui_cell_ft">
	<i class="weui_icon_warn"></i>
	</div>
</div>
<?php }?>

<form name="sign-up" method='post' action=''>
	<div class="weui_cells_title">报名信息:</div>
	<div class="weui_cells weui_cells_form">
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="name" class="weui-label">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="name" name="name" value="<?php echo $this->name?>" placeholder="请输入您的姓名" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="cell" class="weui-label">电话号码:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="cell" name="cell" value="<?php echo $this->cell?>" placeholder="请输入您的电话号码" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell weui_cell_select">
			<div class="weui_cell_hd weui_select_after">性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别:</div>
			<div class="weui_cell_bd weui_cell_primary">
				<select class="weui_select" name="sex">
					<option value="male">男</option>
					<option value="female">女</option>
				</select>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="id-number" class="weui-label">身份证号:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="id-number" name="idNumber" value="<?php echo $this->idNumber?>" placeholder="请输入您的身份证号码" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_btn_area"><button class="weui_btn weui_btn_primary">提交信息</button></div>
	</div>
</form>