<?php if($this->errorMsg != "") {?>
<div class="weui_cell weui_cell_warn">
	<div class="weui_cell_bd weui_cell_primary">
		<p style="color: #F43530;"><?php echo $this->errorMsg?></p>
	</div>
	<div class="weui_cell_ft">
	<i class="weui_icon_warn"></i>
	</div>
</div>
<?php }?>

<h3 class="title">报名信息填写</h3>
<p class="apply-info">
	您的报名信息我们不会向任何无关个人或单位泄漏，此信息仅供中国好声音湖北赛区联系和验证身份使用，请务必填写真实信息以免联系不上。
</p>

<form id="j-applicant-form" name="sign-up" method='post' action=''>
	<div class="weui_cells weui_cells_form">
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="name" class="weui-label">姓名:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="name" name="name" value="<?php echo $this->applicantDoc->getName()?>" placeholder="请输入您的姓名" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="mobile" class="weui-label">电话号码:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="mobile" name="mobile" value="<?php echo $this->applicantDoc->getMobile()?>" placeholder="请输入您的电话号码" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="id-number" class="weui-label">身份证号:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="id-number" name="info_idNumber" value="<?php echo $this->applicantDoc->getInfo()['idNumber']?>" placeholder="请输入您的身份证号码" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_btn_area"><button id="j-post-form" class="weui_btn wx-btn-primary">提交信息</button></div>
		<br>
	</div>
</form>
<script>
	$().ready(function(){
		var applicantForm = $('#j-applicant-form');
		$('#j-post-form').on('click', function(e){
			e.preventDefault();
			var name = applicantForm.find("input[name='name']").val();
			var mobile = applicantForm.find("input[name='mobile']").val();
			var idNumber = applicantForm.find("input[name='info_idNumber']").val();
			if(name && mobile && idNumber){
				var telReg = !!mobile.match(/^(0|86|17951)?(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$/);
				var idNumberReg = /(^\d{15}$)|(^\d{18}$)|(^\d{17}(\d|X|x)$)/;
				if(!telReg){
					$.dialog({
	                    title: 'alert',
	                    content: "请填写正确的手机号码!",
	                    okText: '确定',
	                    ok: function(){}
	                });
	                return;
				}
				if(!idNumberReg.test(idNumber)){
					$.dialog({
	                    title: 'alert',
	                    content: "请填写正确的身份证号!",
	                    okText: '确定',
	                    ok: function(){}
	                });
	                return;
				}
				applicantForm.submit();
			}else {
				$.dialog({
                    title: 'alert',
                    content: "请填写完整信息!",
                    okText: '确定',
                    ok: function(){}
                });
                return;
			}
		});
	});
</script>