<?php if($this->errorMsg != "") {?>
<div class="weui_cell weui_cell_warn">
	<div class="weui_cell_bd weui_cell_primary">
		<p style="color: #F43530;"><?php echo $this->errorMsg?></p>
	</div>
	<div class="weui_cell_ft">
	<i class="weui_icon_warn"></i>
	</div>
</div>
<?php }?>

<h3 class="title">报名信息填写</h3>
<p class="apply-info">
	您的报名信息我们不会向任何无关个人或单位泄漏，此信息仅供中国好声音湖北赛区联系和验证身份使用，请务必填写真实信息以免联系不上。
</p>

<form name="sign-up" method='post' action=''>
	<div class="weui_cells weui_cells_form">
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="name" class="weui-label">姓名:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="name" name="name" value="<?php echo $this->name?>" placeholder="请输入您的姓名" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="mobile" class="weui-label">电话号码:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="mobile" name="mobile" value="<?php echo $this->mobile?>" placeholder="请输入您的电话号码" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="id-number" class="weui-label">身份证号:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="id-number" name="info_idNumber" value="<?php echo $this->info_idNumber?>" placeholder="请输入您的身份证号码" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_btn_area"><button class="weui_btn weui_btn_primary wx-btn-primary">提交信息</button></div>
		<br>
	</div>
</form>