<?php if($this->errorMsg != "") {?>
<div class="weui_cell weui_cell_warn">
	<div class="weui_cell_bd weui_cell_primary">
		<p style="color: #F43530;"><?php echo $this->errorMsg?></p>
	</div>
	<div class="weui_cell_ft">
	<i class="weui_icon_warn"></i>
	</div>
</div>
<?php }?>
<img width="100%" src="http://qs-pm.fucms.com/561776e44de2a1b18dea66ce/o_1a25ha7sp15t815mp15r41l75123q7.jpg">
<form method='post' action=''>
	<div class="weui_cells_title">关联账号</div>
	<div class="weui_cells weui_cells_form">
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="loginName" class="weui_label">用户名:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input id="loginName" class="weui_input" name="loginName" value="<?php echo $this->loginName?>" type="text" placeholder="请输入用户名">
			</div>
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="password" class="weui_label">密&nbsp;&nbsp;&nbsp;&nbsp;码:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input id="password" class="weui_input" name="password" type="password" placeholder="请输入密码">
			</div>
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<br />
		<div class="weui_btn_area"><button class="weui_btn weui_btn_primary">绑定用户</button></div>
	</div>
</form>