<div class="sn-info">
	<div class='winning-banner'><div class='text'>恭喜您中奖了</div></div>
	<div class='well'>
		<?php echo $this->prizeType?>
		<br /><br /><br />
		<h2><?php echo $this->prizeName?></h2>
		<br />
		<h2><span>兑奖密码: </span><?php echo $this->snCode?></h2>
		<br /><br /><br />
		<div class='account-link'>
			您的兑奖密码已经保存到了 <a style='border-radius: 2px; background: #2CFC4D; display: inline-block;padding: 5px; color: white;' href='/<?php echo $this->websiteId?>/user'>我的账户</a>
		</div>
		<div class='panel' style='text-align: left; margin-top: 10px; padding: 10px;'>
			<div class='panel-heading' style='border-bottom:  1px solid #ddd;padding: 10px 0;'>兑奖说明</div>
			<div class='panel-body' style='line-height: 1.5em;padding: 10px 0;'>
				<?php echo $this->awardInfo?>
			</div>
		</div>
		
	</div>
</div>

<?php $this->headLink()->appendStylesheet($this->path('wxs.fucms').'/smashing/style/style.css'); ?>