<style>
	* {margin: 0; padding: 0;}
	body { background-size: cover;background-image:url(http://public-media.qiniudn.com/55249459bd04bfd40b8b4567/smashing-bg-sn-info.jpg?imageView2/2/w/320/interlace/1&v=212);}
	h1 { font: 28px/65px "微软雅黑"; color: #ffe500;}
	h2 { font-size: 22px; line-height: 45px; color: #fff;}
	h1,h2 {text-align: center;}
	p { margin-top: 30px; font: 18px/32px "黑体"; color: #fff;}
</style>
<div class="sn-info">
	<div style="margin-top: 250px; padding: 0 50px;">
		<h1><?php echo $this->prizeType?></h1>
		<h2><?php echo $this->prizeName?></h2>
		<h2><span>SN码:</span><?php echo $this->snCode?></h2>
		<p><?php echo $this->awardInfo?></p>
	</div>
</div>