<?php echo $this->doctype(); ?>

<html>
<head>
	<title><?php echo $this->title ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="renderer" content="webkit" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	
	<script src="<?php echo $this->path('src')?>/zepto/1.1.4/zepto.min.js"></script>
	<script src="<?php echo $this->path('src')?>/zepto/1.1.4/zepto.fx.js"></script>
	<script src="<?php echo $this->path('src')?>/zepto/plugin/tiny-alert/zepto.alert.js"></script>
	
	<link href="<?php echo $this->path('src')?>/zepto/plugin/tiny-alert/zepto.alert.css" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->path('wxs.fucms')?>/common/style/style.css" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->path('wxs.fucms')?>/common/style/weui.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->path('wxs.fucms')?>/icomoon/style.css" rel="stylesheet" type="text/css">
	
	<?php echo $this->headLink()?>
</head>
<body>
	<header>
		<img style='width: 100%;' src='<?php echo $this->outputImage($this->wx_header)?>' />
	</header>
	<content>
	<?php echo $this->content; ?>
	</content>
	<footer style='padding: 2em; margin-top: 2em; border-top: 2px solid #777;'>
		<strong>湖北赛区报名咨询方式</strong>
		<ul>
			<li>报名咨询电话：</li>
			<li>027-86818899</li>
			<li>报名咨询地址：</li>
			<li>湖北省武汉市武昌民主路788号保利大酒店一楼0103室(位于地铁2号线及4号线换乘站洪山广场站A出口)</li>
		</ul>
	</footer>
</body>
</html>