<?php echo $this->doctype(); ?>

<html>
<head>
	<title><?php echo $this->title ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="renderer" content="webkit" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	<script src="https://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
	<script src="<?php echo $this->path('src')?>/jquery/2.1.1/jquery.min.js"></script>
	
	<script src="<?php echo $this->path('src')?>/zepto/plugin/tiny-alert/zepto.alert.js"></script>
	<script src="<?php echo $this->path('wxs.fucms')?>/live-event/script/candidate.js?v=11101107"></script>
	
	<link href="<?php echo $this->path('src')?>/zepto/plugin/tiny-alert/zepto.alert.css" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->path('wxs.fucms')?>/common/style/style.css?v=1106115" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->path('wxs.fucms')?>/common/style/weui.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->path('wxs.fucms')?>/icomoon/style.css" rel="stylesheet" type="text/css">
	
	<link href="<?php echo $this->path('wxs.fucms')?>/live-event/style/live-event.css?v=1107" rel="stylesheet" type="text/css">
	
	<?php echo $this->headLink()?>
</head>
<body>
	<header>
		<img style='width: 100%;' src='//qs-pm.fucms.com/561776e44de2a1b18dea66ce/o_1a36bcbta1uad1cc2n70m8lp817.png' />
	</header>
	<content>
	<?php echo $this->content; ?>
	</content>
	<footer>
		<p>Copyright© 2015 好声音全国海选湖北赛区. ALL Rights Reserved</p>
	</footer>
	<div id="loadingToast" class="weui_loading_toast" style="display: none;">
		<div class="weui_mask_transparent"></div>
			<div class="weui_toast">
				<div class="weui_loading">
				<div class="weui_loading_leaf weui_loading_leaf_0"></div>
				<div class="weui_loading_leaf weui_loading_leaf_1"></div>
				<div class="weui_loading_leaf weui_loading_leaf_2"></div>
				<div class="weui_loading_leaf weui_loading_leaf_3"></div>
				<div class="weui_loading_leaf weui_loading_leaf_4"></div>
				<div class="weui_loading_leaf weui_loading_leaf_5"></div>
				<div class="weui_loading_leaf weui_loading_leaf_6"></div>
				<div class="weui_loading_leaf weui_loading_leaf_7"></div>
				<div class="weui_loading_leaf weui_loading_leaf_8"></div>
				<div class="weui_loading_leaf weui_loading_leaf_9"></div>
				<div class="weui_loading_leaf weui_loading_leaf_10"></div>
				<div class="weui_loading_leaf weui_loading_leaf_11"></div>
			</div>
			<p class="weui_toast_content">加载中...</p>
		</div>
	</div>
</body>
</html>