<form id="upload-form">
	<div class="weui_cells_title">人气榜封面:</div>
	<div class="weui_cells weui_cells_form">
		<div class="weui_cell">
			<div id='pickfiles' style='padding:30px;border:2px dashed #777;'>
				<?php if($this->candidateDoc->getCover() == "") {?>
				<img id='candidate-cover' src='<?php echo $this->outputImage('default-cover.jpg', 200, 200)?>' />
				<?php } else {?>
				<img id='candidate-cover' src='<?php echo $this->outputImage($this->candidateDoc->getCover(), 200, 200)?>' />
				<?php }?>
			</div>
		</div>
	</div>
</form>

<?php if($this->errorMsg != "") {?>
<div class="weui_cell weui_cell_warn">
	<div class="weui_cell_bd weui_cell_primary">
		<p style="color: #F43530;"><?php echo $this->errorMsg?></p>
	</div>
	<div class="weui_cell_ft">
	<i class="weui_icon_warn"></i>
	</div>
</div>
<?php }?>

<form name="sign-up" method='post' action=''>
	<div class="weui_cells_title">您的榜单信息，此信息将向所有人公开，请尽量完善，展示您最好的个人形象</div>
	<div class="weui_cells weui_cells_form">
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="nickname" class="weui-label">榜单名:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="nickname" name="nickname" value="<?php echo $this->candidateDoc->getNickname()?>" placeholder="请输入榜单名，不需要是真名" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell weui_cell_select">
			<div class="weui_cell_hd weui_select_after">性别:</div>
			<div class="weui_cell_bd weui_cell_primary">
				<select class="weui_select" name="sex">
					<option value="male">男</option>
					<option value="female">女</option>
				</select>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="brief" class="weui-label">简介:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<textarea style="color: #000;" class='weui_textarea' id='brief' name='brief'><?php echo $this->candidateDoc->getBrief()?></textarea>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
	</div>
	<br>
	<div class="weui_btn_area"><button class="weui_btn wx-btn-primary">提交信息</button></div>
	<br>
</form>

<script src="<?php echo $this->path('wxs.fucms')?>/file/js/plupload.full.min.js"></script>
<script src="<?php echo $this->path('wxs.fucms')?>/file/js/qiniu.min.js"></script>

<script>
var websiteId = "<?php echo $this->websiteId?>";
var eventId = "<?php echo $this->eventId?>";
var applicantId = '<?php echo $this->applicantId?>';

var qiniuDomain = "<?php echo $this->path('qiniu')?>";
var fileResourceId = eventId + ':' + applicantId;

var browserBtn = $('#pickfiles');
var uploader = Qiniu.uploader({
	runtimes: 'html5',
	browse_button: browserBtn,
	uptoken: '<?php echo $this->uptoken?>',
	unique_names: false,
	domain: qiniuDomain,
	max_file_size: '8mb',
	max_retries: 0,
	dragdrop: false,
	chunk_size: '4mb',
	auto_start: true,
	init: {
		'FilesAdded': function(up, files) {
			//second in seq
			var filenames = new Array();
		},
		'BeforeUpload': function(up, file) {
			$('#upload-form').css('display', 'none');
			$('#replace-text').css('display', 'block');
		},
		'UploadProgress': function(up, file) {
			$('#upload-bar').innerHTML = file.percent;
		},
		'ChunkUploaded': function(up, file) {
			
		},
		'FileUploaded': function(up, file, info) {
			var infoObj = JSON.parse(info);
			
		 	$.ajax({
				url: '/wxsrs/<?php echo $this->websiteId?>/ler-vote-candidate.json/<?php echo $this->candidateId?>',
		 		type: 'PUT',
		 		data: {
			 		'resourceType': 'live-event:candidate:cover',
					'resourceId': fileResourceId,
					'filename': file.name,
					'urlname': file.urlname,
					'size': file.size,
					'mimeType': infoObj.mimeType,
					'ext': infoObj.ext,
					'cover': file.urlname
			 	},
		 		success: function (response) {
		 			$('#candidate-cover').attr('src', qiniuDomain + '/' + websiteId + '/' + file.urlname + '?imageView2/1/w/200/h/200');
			 		
		 			//alert('照片上传成功');
		 		},
		 		error: function (response) {
		 			alert('sorry, 图片上传失败');
		 		}
		 	});

// 			$ajax({
//				url: '/wxsrs/<?php echo $this->websiteId?>/lers-vote-candidate.json/',
// 		 		type: 'POST',
// 		 		data: {
// 					'cover': file.urlname
// 			 	},
// 		 		success: function (response) {
			 		
// 			 		$('#candidate-cover').attr('src', qiniuDomain + '/' + websiteId + '/' + file.urlname + '?imageView2/1/w/200/h/200');
// 		 			//alert('照片上传成功');
// 		 		},
// 		 		error: function (response) {
// 		 			alert('sorry, 图片上传失败');
// 		 		}
// 			});
		 	
		},
		'UploadComplete': function() {
			$('#upload-form').css('display', 'block');
			$('#replace-text').css('display', 'none');


			//$('#')
			
		},
		'Key': function(up, file) {
			//first in seq
			var key, ext;
			var ext;
			var tempArr = file.name.split(".");
			if (tempArr.length === 1 || (tempArr[0] === "" && tempArr.length === 2)) {
				ext = "";
			} else {
				ext = tempArr.pop().toLowerCase();
			}
			key = ext ? file.id + '.' + ext : file.id;
			
			file.urlname = key;
			
			return websiteId + '/' + key;
		}
	}
});
</script>