<?php if($this->errorMsg != "") {?>
<div class="weui_cell weui_cell_warn">
	<div class="weui_cell_bd weui_cell_primary">
		<p style="color: #F43530;"><?php echo $this->errorMsg?></p>
	</div>
	<div class="weui_cell_ft">
	<i class="weui_icon_warn"></i>
	</div>
</div>
<?php }?>

<form id="upload-form">
	<div class="weui_cells_title">人气榜封面:</div>
	<div class="weui_cells weui_cells_form">
		<div class="weui_cell">
			<div id='pickfiles' style='padding:30px;border:2px dashed #777;'>UPLOAD FILES</div>
		</div>
	</div>
</form>

<form name="sign-up" method='post' action=''>
	<div class="weui_cells_title">人气榜信息:</div>
	<div class="weui_cells weui_cells_form">
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="name" class="weui-label">榜单名:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="nickname" name="nickname" value="<?php echo $this->nickname?>" placeholder="请输入您会员名" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="decription" class="weui-label">简介:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<textarea class='weui_textarea' id='decription' name='decription'><?php echo $this->description?></textarea>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell weui_cell_select">
			<div class="weui_cell_hd weui_select_after">性别:</div>
			<div class="weui_cell_bd weui_cell_primary">
				<select class="weui_select" name="sex">
					<option value="male">男</option>
					<option value="female">女</option>
				</select>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_hd">
				<label for="hobby" class="weui-label">兴趣爱好:</label>
			</div>
			<div class="weui_cell_bd weui_cell_primary">
				<input class="weui_input" type="text" id="hobby" name="hobby" value="<?php echo $this->hobby?>" placeholder="请输入您的兴趣爱好" required>
			</div>			
			<div class="weui_cell_ft">
				<i class="weui_icon_warn"></i>
			</div>
		</div>
		<div class="weui_btn_area"><button class="weui_btn weui_btn_primary">提交信息</button></div>
	</div>
</form>

<script src="<?php echo $this->path('wxs.fucms')?>/file/js/plupload.full.min.js"></script>
<script src="<?php echo $this->path('wxs.fucms')?>/file/js/qiniu.min.js"></script>

<script>
var candidateId = '<?php echo $this->candidateId?>';

$('#save-user').on('click', function(e) {
	e.preventDefault();
	var candidateInfo = $('#user-info').serializeArray();

// 	var postInfo = {};
// 	for(var i = 0; i < applicantInfo.length; i++) {
// 		postInfo[applicantInfo[i]['name']] = applicantInfo[i]['value'];
// 	}

	if(candidateId == '') {
		$.post(
			'/wxsrs/<?php echo $this->websiteId?>/lers-vote-candidate.json',
			{openid:'<?php echo $this->openid?>', eventId:'<?php echo $this->eventId?>', info:postInfo},
			function(response) {
				candidateId = response.id;
				alert('人气榜信息已保存！！');
			}
		);
	} else {
		$.ajax({
			url: '/wxsrs/<?php echo $this->websiteId?>/lers-vote-candidate.json/' + candidateId,  
	 		type: 'PUT',  
	 		data: {eventId:'<?php echo $this->eventId?>', info:postInfo},
	 		success: function (response) {
	 			alert('人气榜信息已更新');
	 		},
		});
	}
});

var websiteId = "<?php echo $this->websiteId?>";

var browserBtn = $('#pickfiles');

var uploader = Qiniu.uploader({
	runtimes: 'html5',
	browse_button: browserBtn,
	uptoken: '<?php echo $this->uptoken?>',
	unique_names: false,
	domain: '<?php echo $this->path('qiniu')?>',
	max_file_size: '8mb',
	max_retries: 0,
	dragdrop: false,
	chunk_size: '4mb',
	auto_start: true,
	init: {
		'FilesAdded': function(up, files) {
			//second in seq
			var filenames = new Array();
		},
		'BeforeUpload': function(up, file) {
			$('#upload-form').css('display', 'none');
			$('#replace-text').css('display', 'block');
		},
		'UploadProgress': function(up, file) {
			$('#upload-bar').innerHTML = file.percent;
		},
		'ChunkUploaded': function(up, file) {
			
		},
		'FileUploaded': function(up, file, info) {
			var infoObj = JSON.parse(info);
			
		 	$.ajax({  
				url: '/wxsrs/<?php echo $this->websiteId?>/fr-file.json',
		 		type: 'POST',
		 		data: {
			 		'resourceType': 'live-event:candidate:cover',
					'resourceId': '<?php echo $this->eventId?>',
					'filename': file.name,
					'urlname': file.urlname,
					'size': file.size,
					'mimeType': infoObj.mimeType,
					'ext': infoObj.ext
			 	},
		 		success: function (response) {
		 			alert('照片上传成功');
		 		},
		 		error: function (response) {
		 			alert('sorry, 图片上传失败');
		 		}
		 	});
		},
		'UploadComplete': function() {
			$('#upload-form').css('display', 'block');
			$('#replace-text').css('display', 'none');
		},
		'Key': function(up, file) {
			//first in seq
			var key, ext;
			var ext;
			var tempArr = file.name.split(".");
			if (tempArr.length === 1 || (tempArr[0] === "" && tempArr.length === 2)) {
				ext = "";
			} else {
				ext = tempArr.pop().toLowerCase();
			}
			key = ext ? file.id + '.' + ext : file.id;
			
			file.urlname = key;
			
			return websiteId + '/' + key;
		}
	}
});
</script>