<div class="candidate" style="background-color: <?php echo "#000" ?>">
	<img class="logo" alt="logo.jpg" src="http://wxres.skwy.com/page/img/shpaint/header.jpg">
	<div class="warp">
		<div class="vote-box">
			<div class="vote-top-bar">
				<span class="vote-number">98</span>
				<span class="vote-number-text">号</span>
				<strong class="name">叶凡</strong>
			</div>
			<div class="vote-main">
				<div class="vote-img">
					<img src="https://dn-skwy-p01.qbox.me/editorp/1445958460.jpeg-thumbnail320">
				</div>
				<div class="vote-title">《唱响中国》</div>
				<div class="vote-button">
					<a class="weui_btn weui_btn_primary J-vote-btn">支持TA</a>
				</div>
				<div class="vote-info">
					<div class="count">
						<div id="J-votes-id">2698</div>
						<p>已得票数</p>
					</div>
				</div>
			</div>
			                
			<div class="vote-button">
				<a class="back-button weui_btn weui_btn_default" href="">前往投票广场</a>
				<div class="button-group">
					<div class="button-box">
						<a class="weui_btn weui_btn_plain_primary" href="">我也要报名</a>
					</div>
					<div class="button-box">
						<a class="weui_btn weui_btn_plain_default" href="">比赛规则</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php $this->headLink()->appendStylesheet($this->path('wxs.fucms').'/live-event/style/candidate.css'); ?>