<div class="candidate">
	<div class="warp">
		<div class="vote-box">
			<div class="vote-top-bar">
				<strong class="name"><?php echo $this->candidateDoc->getNickname()?></strong>
			</div>
			<div class="vote-main">
				<div class="vote-img">
					<img width="100%" src="<?php echo $this->outputImage($this->candidateDoc->getCover(), 320, 480)?>">
				</div>
				<div class="vote-info">
					<div class="count">
						<div id="j_vote_disp-<?php echo $this->candidateDoc->getId()?>"><?php echo $this->candidateDoc->getTicketCount()?></div>
						<p>已得票数</p>
					</div>
				</div>
				<div class="vote-brief" style="text-align: center; margin: .1rem 0;padding: 0 5%;">
					<dl>
						<dt style="font-size: .18rem;margin: .05rem 0;">个人介绍</dt>
						<dd style="line-height: .24rem;"><?php echo $this->candidateDoc->getBrief()?></dd>
					</dl>
				</div>
				<div class="vote-button">
					<button
						id='j_vote_btn-<?php echo $this->candidateDoc->getId()?>'
						vote-url='<?php echo $this->url('wxsrs/restroutes', array('controller' => 'ler-vote-ticket', 'id' => $this->candidateDoc->getId()), true)?>'
						class="weui_btn wx-btn-primary"
					>支持TA</button>
				</div>
			</div>
			<!-- div class="vote-button">
				<a class="back-button weui_btn wx-btn-primary"
				href="<?php echo $this->url('wxs/wildcard', array('websiteId' => $this->websiteId, 'controller' => 'le-vote-candidate', 'action' => 'list', 'eventId' => $this->eventId))?>"
				>
					前往人气榜
				</a>
				<div class="button-group">
					<div class="button-box">
						<a class="weui_btn wx-btn-default"
						href="<?php echo $this->url('wxs/wildcard', array('websiteId' => $this->websiteId, 'controller' => 'le-index', 'action' => 'index', 'eventId' => $this->eventId))?>"
						>
							我也要报名
						</a>
					</div>
					<div class="button-box">
						<a class="weui_btn wx-btn-default" href="">比赛规则</a>
					</div>
				</div>
				<div style="width: 70%; margin: .15rem auto;">
					<a class="weui_btn wx-btn-info j-view-wx-share-box">叫小伙伴们来投票!</a>
				</div>
				<br />
				<a class="weui_btn wx-btn-default" href="http://www.chvoice.com/public/register">进入秀立方官方报名入口</a>
			</div-->
		</div>
	</div>
</div>

<?php $this->headLink()->appendStylesheet($this->path('wxs.fucms').'/live-event/style/candidate.css?v=1106115'); ?>
<script>
	wx.config(<?php echo $this->wxConfig?>);
	wx.ready(function(){
		wx.onMenuShareTimeline({
		    title: '<?php echo $this->candidateDoc->getNickname()?>参加了中国好声音湖北赛区海选比赛，朋友们快来为他投票吧!',
		    link: window.location.href,
		    imgUrl: '<?php echo $this->outputImage($this->candidateDoc->getCover(), 320, 480)?>',
		    success: function () {
		    },
		    cancel: function () {
		    }
		});
		wx.onMenuShareAppMessage({
		    title: '第五季中国好声音海选湖北赛区',
		    desc: '<?php echo $this->candidateDoc->getNickname()?>参加了第五季中国好声音湖北赛区海选比赛，朋友们快来为他投票吧!',
		    link: window.location.href,
		    imgUrl: '<?php echo $this->outputImage($this->candidateDoc->getCover(), 320, 480)?>',
		    type: '',
		    dataUrl: '',
		    success: function () { 
		    },
		    cancel: function () { 
		    }
		});
	});

	$().ready(function(){
		$('.j-view-wx-share-box').on('click', function(){
			$('body').append("<div class=\"share-box j-wx-share-box\"></div>");
			$('.j-wx-share-box').on('click', function(){
				$(this).remove();
			});
		});
	});
</script>