<div class="candidate-list" style="background-color: <?php echo "#000" ?>">
	<div class="warp">
		<div class="vote-box">
			<div class="vote-button">
				<div class="button-group">
					<div class="button-box">
						<a class="weui_btn weui_btn_primary" href="">我也要报名</a>
					</div>
					<div class="button-box">
						<a class="weui_btn weui_btn_plain_default" href="">比赛规则</a>
					</div>
				</div>
			</div>
		</div>
		<div class="vote-list">
			<?php foreach($this->candidateDocs as $candidateDoc) {?>
			<div class="vote-item">
				<a class="vote-view" href="<?php //echo $this->url('wxs/wildcard', array('websiteId')?>">
					<img src="<?php echo $this->outputImage($candidateDoc->getCover(), 160, 240) ?>" alt="">
					<span class="number">112</span>
					<div class="ballot-info">
						<span class="mc">第一名</span>
						<div class="ps">票数:<?php echo $candidateDoc->getTicketCount()?></div>
					</div>
				</a>
				<div class="info-box">
					<div class="name"><strong><?php echo $candidateDoc->getNickname()?></strong></div>
					<div class="button-box">
						<a class="weui_btn weui_btn_plain_primary" href="">支持TA</a>
					</div>
				</div>
			</div>
			<?php }?>
		</div>
	</div>
</div>
<?php $this->headLink()->appendStylesheet($this->path('wxs.fucms').'/live-event/style/candidate.css'); ?>

<!-- websiteId -->