<div class="candidate-list" style="background-color: <?php echo "#000" ?>">
	<div class="warp">
		<div class="vote-box" style="padding: 0 3%;">
			<div class="vote-button">
				<div class="button-group">
					<div class="button-box">
						<a class="weui_btn wx-btn-primary" 
							href="<?php echo $this->url('wxs/wildcard', array('websiteId' => $this->websiteId, 'controller' => 'le-index', 'action' => 'index', 'eventId' => $this->eventId))?>">我也要报名</a>
					</div>
					<div class="button-box">
						<a class="weui_btn wx-btn-primary" href="">比赛规则</a>
					</div>
				</div>
			</div>
		</div>
		<div class="search">
			<form name="search">
				<input id="j-vote-search-value" type="text" placeholder="输入参赛者编号或姓名 ">
				<a id="j-vote-search-btn" class="btn-search">搜索</a>
			</form>			
		</div>
		<div class="vote-list">
			<?php foreach($this->candidateDocs as $candidateDoc) {?>
			<div class="vote-item">
				<a class="vote-view" href="<?php echo $this->url('wxs/wildcard', array('action' => 'index', 'candidateId' => $candidateDoc->getId()), true)?>">
					<img src="<?php echo $this->outputImage($candidateDoc->getCover(), 160, 240) ?>" alt="">
					<span class="vote-info"><?php echo $candidateDoc->getId()?></span>
					<div class="tickt-count">
						<div class="ps">票数:<span id="j_vote_disp-<?php echo $candidateDoc->getId()?>"><?php echo $candidateDoc->getTicketCount()?></span></div>
					</div>
				</a>
				<div class="info-box">
					<div class="name"><strong><?php echo $candidateDoc->getNickname()?></strong></div>
					<div class="button-box">
						<button
							id='j_vote_btn-<?php echo $candidateDoc->getId() ?>'
							vote-url='<?php echo $this->url('wxsrs/restroutes', array('controller' => 'ler-vote-ticket', 'id' => $candidateDoc->getId()), true)?>'
							class="wx-vote-btn" href=""
						>支持TA</a>
					</div>
				</div>
			</div>
			<?php }?>
		</div>
	</div>
</div>
<?php $this->headLink()->appendStylesheet($this->path('wxs.fucms').'/live-event/style/candidate.css?v=11061115'); ?>
<script>
	$().ready(function(){
		$('#j-vote-search-btn').on('click', function(){
			var value = $('#j-vote-search-value').val();
			value = value.replace(/(^\s*)|(\s*$)/g,'');
			if(value){
				$.ajax({
					url: location.href,
			 		type: 'POST',
			 		data: {
				 		'id': value
				 	},
			 		success: function (resp) {
			 			if(resp.status == 'error'){
			 				$.dialog({
			                    title: 'alert',
			                    content: resp.errMsg,
			                    okText: '确定',
			                    ok: function(){}
			                });
				 		}else if(resp.status == 'success'){
					 		var url = resp.url;
							location.href = url;
					 	}
			 		}
			 	});
			}
		});
	});
</script>

<!-- websiteId -->