<div class='user-banner'>
	<img src='<?php echo $this->path('wxs.fucms')?>/user/image/banner-vip.jpg' />
</div>
<ul class='nav-list'>
	<li>
		<a href='<?php echo $this->url('user/actionroutes', array('controller' => 'user-sn', 'action' => 'index'), true)?>'>
			<i class='icon-redeem pull-left'></i>
			<div class='text'>我的兑换码</div>
			<i class='icon-keyboard-arrow-right pull-right'></i>
		</a>
	</li>
</ul>