aa

<div class='upload-image'>
	上传照片
</div>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script>
	wx.config(<?php echo $this->wxConfig?>);
	wx.ready(function(){
		alert('wx.ready');
	});
	wx.error(function(res){
		alert('error');
		alert(res.msg);
	});

	$('.upload-image').click(function() {
		alert('btn-clicked');
		wx.chooseImage({
		    count: 1, // 默认9
		    sizeType: ['original', 'compressed'], // 可以指定是原图还是压缩图，默认二者都有
		    sourceType: ['album', 'camera'], // 可以指定来源是相册还是相机，默认二者都有
		    success: function (res) {
		        var localIds = res.localIds; // 返回选定照片的本地ID列表，localId可以作为img标签的src属性显示图片

				alert(localIds);




				wx.uploadImage({
				    localId: localIds, // 需要上传的图片的本地ID，由chooseImage接口获得
				    isShowProgressTips: 1, // 默认为1，显示进度提示
				    success: function (res) {
				        var serverId = res.serverId; // 返回图片的服务器端ID


				        alert(serverId);
				    }
				});
		        
		    }
		});
	});
</script>