<div class="profile-box">
	<div class="weui_cells">
		<div class="weui_cell">
			<div class="weui_cell_bd weui_cell_primary">
				<p>头像</p>
			</div>
			<div class="weui_cell_ft"><img width="55px" src="http://7fvjw0.com1.z0.glb.clouddn.com/547d70e3ce2350bc0d000029/avatar.jpg" alt="avatar.jpg"></div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_bd weui_cell_primary">
				<p>姓名</p>
			</div>
			<div class="weui_cell_ft"><?php echo $this->applicantInfo['name']?></div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_bd weui_cell_primary">
				<p>身份证号</p>
			</div>
			<div class="weui_cell_ft"><?php echo $this->applicantInfo['idNumber']?></div>
		</div>
	</div>
	<div class="weui_cells">
		<div class="weui_cell">
			<div class="weui_cell_bd weui_cell_primary">
				<p>性别</p>
			</div>
			<div class="weui_cell_ft"><?php echo $this->applicantInfo['sex']?></div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_bd weui_cell_primary">
				<p>电话</p>
			</div>
			<div class="weui_cell_ft"><?php echo $this->applicantDoc->getMobile()?></div>
		</div>
	</div>
</div>

<?php
if($this->voteActivated) {
?>
<div>为我拉票</div>

<?php if($this->voteConfig['candidateStatus'] == 'not-found') {?>
在正式为您自己拉票之前，需要创建一份拉票的档案，此档案中的内容会向公众公开
<a href="<?php echo $this->url('wxs/wildcard', array('controller' => 'le-vote-candidate', 'action' => 'edit'), true)?>" class="weui_btn weui_btn_mini weui_btn_default">创建档案</a>
<?php }?>

<?php if($this->voteConfig['candidateStatus'] == 'not-complete') {?>
人气榜拉票信息没有填写完整，
<a href="<?php echo $this->url('wxs/wildcard', array('controller' => 'le-vote-candidate', 'action' => 'edit'), true)?>" class="weui_btn weui_btn_mini weui_btn_default">完善信息</a>
只有完整的信息才会在人气排行中显示
<?php }?>

<?php if($this->voteConfig['candidateStatus'] == 'complete') {?>
<img src='<?php echo $this->outputImage($this->voteConfig['candidateDoc']->getCover(), 100, 100)?>' />
<div>
	<?php echo $this->voteConfig['candidateDoc']->getNickname()?>
</div>
<a href='<?php echo $this->url('wxs/wildcard', array('controller' => 'le-vote-candidate', 'action' => 'index', 'candidateId' => $this->voteConfig['candidateId']), true)?>'>分享拉票</a>
<a href="<?php echo $this->url('wxs/wildcard', array('controller' => 'le-vote-candidate', 'action' => 'edit'), true)?>" class="weui_btn weui_btn_mini weui_btn_default">修改信息</a>
<?php }?>

<?php
}
?>

<?php if($this->wallActivated) {?>
<div>
	
</div>
<?php }?>

<?php if($this->checkInActivated) {?>
<div>
	
</div>
<?php }?>
