<div class="profile-box">
	<div class="weui_cells">
		<div class="weui_cell">
			<div class="weui_cell_bd weui_cell_primary">
				<p>头像</p>
			</div>
			<div class="weui_cell_ft"><img width="55px" src="http://7fvjw0.com1.z0.glb.clouddn.com/547d70e3ce2350bc0d000029/avatar.jpg" alt="avatar.jpg"></div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_bd weui_cell_primary">
				<p>姓名</p>
			</div>
			<div class="weui_cell_ft"><?php echo "叶凡"?></div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_bd weui_cell_primary">
				<p>身份证号</p>
			</div>
			<div class="weui_cell_ft"><?php echo "420111********319"?></div>
		</div>
	</div>
	<div class="weui_cells">
		<div class="weui_cell">
			<div class="weui_cell_bd weui_cell_primary">
				<p>性别</p>
			</div>
			<div class="weui_cell_ft"><?php echo "男"?></div>
		</div>
		<div class="weui_cell">
			<div class="weui_cell_bd weui_cell_primary">
				<p>住址</p>
			</div>
			<div class="weui_cell_ft"><?php echo "湖北省武汉市"?></div>
		</div>
	</div>
</div>

<?php
if($this->voteActivated) {
?>
<div>为我拉票</div>

<?php if($this->voteConfig['candidateStatus'] == 'not-found') {?>
在正式为您自己拉票之前，需要创建一份拉票的档案，此档案中的内容会向公众公开
<a href="<?php echo $this->url('wxs/wildcard', array('websiteId' => $this->websiteId, 'controller' => 'le-vote-candidate', 'action' => 'edit', 'eventId' => $this->eventId))?>" class="weui_btn weui_btn_mini weui_btn_default">创建档案</a>
<?php }?>

<?php if($this->voteConfig['candidateStatus'] == 'not-complete') {?>
<?php }?>

<?php if($this->voteConfig['candidateStatus'] == 'complete') {?>
<img src='<?php echo $this->candidateDoc->getThumb()?>' />
<div>
	<?php echo $this->candidateDoc->getNickname()?>
</div>
<?php }?>
<?php
}
?>

<?php if($this->wallActivated) {?>
<div>
	
</div>
<?php }?>

<?php if($this->checkInActivated) {?>
<div>
	
</div>
<?php }?>
