<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class PromotionDocumentSnHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['prizeId'])) {
            $value = $data['prizeId'];
            $return = (string) $value;
            $this->class->reflFields['prizeId']->setValue($document, $return);
            $hydratedData['prizeId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['label'])) {
            $value = $data['label'];
            $return = (string) $value;
            $this->class->reflFields['label']->setValue($document, $return);
            $hydratedData['label'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['status'])) {
            $value = $data['status'];
            $return = (string) $value;
            $this->class->reflFields['status']->setValue($document, $return);
            $hydratedData['status'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['serialCode'])) {
            $value = $data['serialCode'];
            $return = (string) $value;
            $this->class->reflFields['serialCode']->setValue($document, $return);
            $hydratedData['serialCode'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['openId'])) {
            $value = $data['openId'];
            $return = (string) $value;
            $this->class->reflFields['openId']->setValue($document, $return);
            $hydratedData['openId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['approvedByLabel'])) {
            $value = $data['approvedByLabel'];
            $return = (string) $value;
            $this->class->reflFields['approvedByLabel']->setValue($document, $return);
            $hydratedData['approvedByLabel'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['approvedById'])) {
            $value = $data['approvedById'];
            $return = (string) $value;
            $this->class->reflFields['approvedById']->setValue($document, $return);
            $hydratedData['approvedById'] = $return;
        }
        return $hydratedData;
    }
}