<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class WxDocumentLiveEventApplicantHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['openId'])) {
            $value = $data['openId'];
            $return = (string) $value;
            $this->class->reflFields['openId']->setValue($document, $return);
            $hydratedData['openId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['eventId'])) {
            $value = $data['eventId'];
            $return = (string) $value;
            $this->class->reflFields['eventId']->setValue($document, $return);
            $hydratedData['eventId'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['info'])) {
            $value = $data['info'];
            $return = $value;
            $this->class->reflFields['info']->setValue($document, $return);
            $hydratedData['info'] = $return;
        }
        return $hydratedData;
    }
}