<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class WxDocumentPromotionAssistanceRecordHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['nickname'])) {
            $value = $data['nickname'];
            $return = (string) $value;
            $this->class->reflFields['nickname']->setValue($document, $return);
            $hydratedData['nickname'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['openId'])) {
            $value = $data['openId'];
            $return = (string) $value;
            $this->class->reflFields['openId']->setValue($document, $return);
            $hydratedData['openId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['headimgurl'])) {
            $value = $data['headimgurl'];
            $return = (string) $value;
            $this->class->reflFields['headimgurl']->setValue($document, $return);
            $hydratedData['headimgurl'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['value'])) {
            $value = $data['value'];
            $return = (float) $value;
            $this->class->reflFields['value']->setValue($document, $return);
            $hydratedData['value'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['aidRecord'])) {
            $value = $data['aidRecord'];
            $return = $value;
            $this->class->reflFields['aidRecord']->setValue($document, $return);
            $hydratedData['aidRecord'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['aidSource'])) {
            $value = $data['aidSource'];
            $return = $value;
            $this->class->reflFields['aidSource']->setValue($document, $return);
            $hydratedData['aidSource'] = $return;
        }
        return $hydratedData;
    }
}