<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class WxDocumentLiveEventApplicantHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['openid'])) {
            $value = $data['openid'];
            $return = (string) $value;
            $this->class->reflFields['openid']->setValue($document, $return);
            $hydratedData['openid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['eventId'])) {
            $value = $data['eventId'];
            $return = (string) $value;
            $this->class->reflFields['eventId']->setValue($document, $return);
            $hydratedData['eventId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['status'])) {
            $value = $data['status'];
            $return = (string) $value;
            $this->class->reflFields['status']->setValue($document, $return);
            $hydratedData['status'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['mobile'])) {
            $value = $data['mobile'];
            $return = (string) $value;
            $this->class->reflFields['mobile']->setValue($document, $return);
            $hydratedData['mobile'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['info'])) {
            $value = $data['info'];
            $return = $value;
            $this->class->reflFields['info']->setValue($document, $return);
            $hydratedData['info'] = $return;
        }
        return $hydratedData;
    }
}