<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class WxDocumentLiveEventVoteCandidateHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['openid'])) {
            $value = $data['openid'];
            $return = (string) $value;
            $this->class->reflFields['openid']->setValue($document, $return);
            $hydratedData['openid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['eventId'])) {
            $value = $data['eventId'];
            $return = (string) $value;
            $this->class->reflFields['eventId']->setValue($document, $return);
            $hydratedData['eventId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['cover'])) {
            $value = $data['cover'];
            $return = (string) $value;
            $this->class->reflFields['cover']->setValue($document, $return);
            $hydratedData['cover'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['nickname'])) {
            $value = $data['nickname'];
            $return = (string) $value;
            $this->class->reflFields['nickname']->setValue($document, $return);
            $hydratedData['nickname'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['brief'])) {
            $value = $data['brief'];
            $return = (string) $value;
            $this->class->reflFields['brief']->setValue($document, $return);
            $hydratedData['brief'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['info'])) {
            $value = $data['info'];
            $return = $value;
            $this->class->reflFields['info']->setValue($document, $return);
            $hydratedData['info'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['pics'])) {
            $value = $data['pics'];
            $return = $value;
            $this->class->reflFields['pics']->setValue($document, $return);
            $hydratedData['pics'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['ticketCount'])) {
            $value = $data['ticketCount'];
            $return = (int) $value;
            $this->class->reflFields['ticketCount']->setValue($document, $return);
            $hydratedData['ticketCount'] = $return;
        }
        return $hydratedData;
    }
}