<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class WxDocumentSettingHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['authorizer_info'])) {
            $value = $data['authorizer_info'];
            $return = $value;
            $this->class->reflFields['authorizer_info']->setValue($document, $return);
            $hydratedData['authorizer_info'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['qrcode_url'])) {
            $value = $data['qrcode_url'];
            $return = (string) $value;
            $this->class->reflFields['qrcode_url']->setValue($document, $return);
            $hydratedData['qrcode_url'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['authorization_info'])) {
            $value = $data['authorization_info'];
            $return = $value;
            $this->class->reflFields['authorization_info']->setValue($document, $return);
            $hydratedData['authorization_info'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['isAddFriendReplyOpen'])) {
            $value = $data['isAddFriendReplyOpen'];
            $return = (bool) $value;
            $this->class->reflFields['isAddFriendReplyOpen']->setValue($document, $return);
            $hydratedData['isAddFriendReplyOpen'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['addFriendAutoreplyInfo'])) {
            $value = $data['addFriendAutoreplyInfo'];
            $return = $value;
            $this->class->reflFields['addFriendAutoreplyInfo']->setValue($document, $return);
            $hydratedData['addFriendAutoreplyInfo'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['defaultReply'])) {
            $value = $data['defaultReply'];
            $return = (string) $value;
            $this->class->reflFields['defaultReply']->setValue($document, $return);
            $hydratedData['defaultReply'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['serviceQrCodeUrl'])) {
            $value = $data['serviceQrCodeUrl'];
            $return = (string) $value;
            $this->class->reflFields['serviceQrCodeUrl']->setValue($document, $return);
            $hydratedData['serviceQrCodeUrl'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['mediaId'])) {
            $value = $data['mediaId'];
            $return = (string) $value;
            $this->class->reflFields['mediaId']->setValue($document, $return);
            $hydratedData['mediaId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['title'])) {
            $value = $data['title'];
            $return = (string) $value;
            $this->class->reflFields['title']->setValue($document, $return);
            $hydratedData['title'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['description'])) {
            $value = $data['description'];
            $return = (string) $value;
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['created'])) {
            $value = $data['created'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['created']->setValue($document, clone $return);
            $hydratedData['created'] = $return;
        }
        return $hydratedData;
    }
}